# Generated by Django 2.2.4 on 2019-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('a_contact_no', models.IntegerField(primary_key=True, serialize=False)),
                ('a_password', models.CharField(max_length=20)),
                ('a_otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('ag_no', models.IntegerField()),
                ('ag_name', models.CharField(max_length=50)),
                ('ag_photo', models.ImageField(upload_to='agent/')),
                ('ag_address', models.TextField()),
                ('ag_contact_no', models.IntegerField()),
                ('ag_username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ag_password', models.CharField(max_length=20)),
                ('ag_otp', models.IntegerField()),
            ],
        ),
    ]
