# Generated by Django 2.2.4 on 2019-08-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('c_name', models.CharField(max_length=30)),
                ('c_contact_no', models.IntegerField()),
                ('c_photo', models.ImageField(upload_to='client/')),
                ('c_address', models.TextField()),
                ('c_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('c_password', models.CharField(max_length=30)),
                ('c_otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_no', models.AutoField(primary_key=True, serialize=False)),
                ('comp_complaint', models.TextField()),
                ('comp_client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
            ],
        ),
    ]
