# Generated by Django 2.2.4 on 2019-08-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_admin', '0001_initial'),
        ('os_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_location', models.CharField(max_length=500)),
                ('p_photo', models.ImageField(upload_to='property/')),
                ('p_size', models.CharField(max_length=50)),
                ('p_prize', models.CharField(max_length=50)),
                ('p_facing', models.CharField(max_length=50)),
                ('p_status', models.CharField(max_length=50)),
                ('p_add_date', models.DateField(auto_now_add=True)),
                ('p_sold_date', models.DateField(auto_now_add=True)),
                ('p_comment', models.CharField(default='Good', max_length=500)),
                ('p_agent_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_admin.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date_of_sold', models.DateField(auto_now_add=True)),
                ('s_client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('s_property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
        migrations.CreateModel(
            name='BlockProperty',
            fields=[
                ('b_block_property_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_block_date', models.DateField(auto_now_add=True)),
                ('b_client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('b_property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
    ]
